export const SET_LOADER_VALUE = "SET_LOADER_VALUE";


export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";


export const SET_CART = "SET_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_PRODUCT = "LOAD_CURRENT_PRODUCT";